# Predicciones — Blind Test Data
## ML Modeling Challenge - Wizeline

Generación de predicciones sobre `blind_test_data.csv` usando el modelo **CatBoost optimizado**
guardado en el Notebook 3.

- Modelo  : cargado desde `models/catboost_optimized.joblib`
- Features : leídas desde `config.yaml`
- Output  : `data/predictions.csv`

## 0. Imports y configuración

In [1]:
from pathlib import Path

import joblib
import plotly.express as px
import polars as pl
import yaml

with open('config.yaml') as f:
    config = yaml.safe_load(f)

FEATURES: list[str] = config['features']['selected']
MODEL_PATH: Path = Path(config['model']['artifact_path'])
BLIND_TEST_PATH: Path = Path(config['data']['blind_test_path'])
OUTPUT_PATH: Path = Path('data/predictions.csv')

print(f'Modelo          : {MODEL_PATH}')
print(f'Features ({len(FEATURES)})   : {FEATURES}')
print(f'Blind test path : {BLIND_TEST_PATH}')
print(f'Output path     : {OUTPUT_PATH}')

Modelo          : models/catboost_optimized.joblib
Features (5)   : ['feature_2', 'feature_13', 'feature_9', 'feature_18', 'feature_11']
Blind test path : data/blind_test_data.csv
Output path     : data/predictions.csv

## 1. Carga del modelo y datos

In [2]:
pipeline = joblib.load(MODEL_PATH)
print(f'Modelo cargado: {type(pipeline.named_steps["model"]).__name__}')
print(f'Parámetros del estimador:')
for k, v in pipeline.named_steps['model'].get_params().items():
    print(f'  {k}: {v}')

Modelo cargado: CatBoostRegressor
Parámetros del estimador:
  iterations: 980
  learning_rate: 0.038518088621849036
  depth: 5
  l2_leaf_reg: 9.56569213287667
  loss_function: RMSE
  random_seed: 5000
  verbose: 0
  subsample: 0.8000817293258272

In [3]:
df_blind = pl.read_csv(BLIND_TEST_PATH)
print(f'Shape blind test : {df_blind.shape}')
print(f'Columnas         : {df_blind.columns}')
df_blind.head()

Shape blind test : (200, 20)
Columnas         : ['feature_0', 'feature_1', 'feature_2', 'feature_3', 'feature_4', 'feature_5', 'feature_6', 'feature_7', 'feature_8', 'feature_9', 'feature_10', 'feature_11', 'feature_12', 'feature_13', 'feature_14', 'feature_15', 'feature_16', 'feature_17', 'feature_18', 'feature_19']

shape: (5, 20)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ feature_0 ┆ feature_1 ┆ feature_2 ┆ feature_3 ┆ … ┆ feature_1 ┆ feature_1 ┆ feature_1 ┆ feature_ │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ 6         ┆ 7         ┆ 8         ┆ 19       │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 676.86761 ┆ 32.518822 ┆ 254.82587 ┆ 502.26851 ┆ … ┆ 121.14746 ┆ 68.284243 ┆ 26.96987  ┆ 314.4615 │
│ 5         ┆           ┆ 5         ┆           ┆   ┆ 6         ┆           ┆           ┆ 82       │
│ 628.69522 ┆ 426.16393 ┆ 347.07028 ┆ 431.10690 ┆ … ┆ 49.163652 ┆ 85.511662 ┆ 33.500538 ┆ 819.5378 │
│ 8         ┆ 3         ┆           ┆ 3         ┆   ┆           ┆           ┆           ┆ 77       │
│ 131.76594 ┆ 323.83966 ┆ 245.39977 ┆ 181.81439 ┆ … ┆ 10.037994 ┆ 62.631938 ┆ 6.211169  ┆ 341.3613 │
│ 3         ┆ 9         ┆ 5         ┆ 8         ┆   ┆           ┆           ┆           ┆ 74       │
│ 160.97019 ┆ 489.71202 ┆ 70.482159 ┆ 309.48626 ┆ … ┆ 149.66149 ┆ 66.415878 ┆ 15.001753 ┆ 539.0874 │
│ 5         ┆ 9         ┆           ┆ 9         ┆   ┆ 3         ┆           ┆           ┆ 09       │
│ 419.90713 ┆ 216.62521 ┆ 487.88786 ┆ 253.70446 ┆ … ┆ 186.94488 ┆ 106.51484 ┆ 3.443809  ┆ 364.3419 │
│ 7         ┆ 9         ┆           ┆ 2         ┆   ┆ 4         ┆ 6         ┆           ┆ 69       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## 2. Generación de predicciones

In [4]:
X_blind = df_blind.select(FEATURES).to_numpy()
predictions = pipeline.predict(X_blind)

df_predictions = df_blind.with_columns(
    pl.Series('target_predicted', predictions)
)

print(f'Predicciones generadas: {len(predictions)}')
print(f'\nEstadísticas de las predicciones:')
print(df_predictions.select('target_predicted').describe())
df_predictions.head()

Predicciones generadas: 200

Estadísticas de las predicciones:
shape: (9, 2)
┌────────────┬──────────────────┐
│ statistic  ┆ target_predicted │
│ ---        ┆ ---              │
│ str        ┆ f64              │
╞════════════╪══════════════════╡
│ count      ┆ 200.0            │
│ null_count ┆ 0.0              │
│ mean       ┆ 14.223496        │
│ std        ┆ 4.961928         │
│ min        ┆ 2.019092         │
│ 25%        ┆ 10.422584        │
│ 50%        ┆ 14.258765        │
│ 75%        ┆ 17.671019        │
│ max        ┆ 25.427945        │
└────────────┴──────────────────┘

shape: (5, 21)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ feature_0 ┆ feature_1 ┆ feature_2 ┆ feature_3 ┆ … ┆ feature_1 ┆ feature_1 ┆ feature_1 ┆ target_p │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ 7         ┆ 8         ┆ 9         ┆ redicted │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 676.86761 ┆ 32.518822 ┆ 254.82587 ┆ 502.26851 ┆ … ┆ 68.284243 ┆ 26.96987  ┆ 314.46158 ┆ 13.02506 │
│ 5         ┆           ┆ 5         ┆           ┆   ┆           ┆           ┆ 2         ┆ 3        │
│ 628.69522 ┆ 426.16393 ┆ 347.07028 ┆ 431.10690 ┆ … ┆ 85.511662 ┆ 33.500538 ┆ 819.53787 ┆ 11.71934 │
│ 8         ┆ 3         ┆           ┆ 3         ┆   ┆           ┆           ┆ 7         ┆ 7        │
│ 131.76594 ┆ 323.83966 ┆ 245.39977 ┆ 181.81439 ┆ … ┆ 62.631938 ┆ 6.211169  ┆ 341.36137 ┆ 15.49515 │
│ 3         ┆ 9         ┆ 5         ┆ 8         ┆   ┆           ┆           ┆ 4         ┆ 6        │
│ 160.97019 ┆ 489.71202 ┆ 70.482159 ┆ 309.48626 ┆ … ┆ 66.415878 ┆ 15.001753 ┆ 539.08740 ┆ 12.63867 │
│ 5         ┆ 9         ┆           ┆ 9         ┆   ┆           ┆           ┆ 9         ┆ 8        │
│ 419.90713 ┆ 216.62521 ┆ 487.88786 ┆ 253.70446 ┆ … ┆ 106.51484 ┆ 3.443809  ┆ 364.34196 ┆ 17.27510 │
│ 7         ┆ 9         ┆           ┆ 2         ┆   ┆ 6         ┆           ┆ 9         ┆ 2        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [5]:
fig = px.histogram(
    x=predictions,
    nbins=30,
    title='Distribución de predicciones — Blind Test',
    labels={'x': 'target_predicted', 'y': 'Frecuencia'},
    color_discrete_sequence=['#636EFA'],
)
fig.update_layout(height=400)
fig.show()

## 3. Guardado de predicciones

In [6]:
df_output = pl.DataFrame({'target_predicted': predictions})

df_output.write_csv(OUTPUT_PATH)

print(f'Predicciones guardadas en : {OUTPUT_PATH}')
print(f'Filas                     : {len(df_output)}')
df_output.head()

Predicciones guardadas en : data/predictions.csv
Filas                     : 200

shape: (5, 1)
┌──────────────────┐
│ target_predicted │
│ ---              │
│ f64              │
╞══════════════════╡
│ 13.025063        │
│ 11.719347        │
│ 15.495156        │
│ 12.638678        │
│ 17.275102        │
└──────────────────┘